name: Deployment Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Azure CLI
        uses: azure/cli-action@v1
      - name: Deploy to Azure
        run: |
          # Set up Azure login and deploy
          az webapp deploy --name <your-app-name> --resource-group <your-resource-group> --src-path ./app